### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by pigreco** [PedroVenancio/qgis_polygon_splitting#1]
Thanks for sharing the script.

I copied and pasted the `QGISPolygonSplitting.py` file into my profile (`C: \ Users \ pigre \ AppData \ Roaming \ QGIS \ QGIS3 \ profiles \ default \ processing \ scripts`),
when `QGIS 3.12` starts, this message appears and QGIS crashes until I click on `close`

```
Si è verificato un errore durante l'esecuzione del codice Python: 

SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\script\ScriptAlgorithmProvider.py", line 119, in loadAlgorithms
    alg = ScriptUtils.loadAlgorithm(moduleName, filePath)
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\script\ScriptUtils.py", line 66, in loadAlgorithm
    spec.loader.exec_module(module)
  File "", line 724, in exec_module
  File "", line 860, in get_code
  File "", line 791, in source_to_code
  File "", line 219, in _call_with_frames_removed
  File "C:\Users\pigre\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\QGISPolygonSplitting.py", line 18
    da qgis.core import QgsProcessing
          ^
SyntaxError: invalid syntax


Versione Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versione di QGIS: 3.12.0-București București, cd141490ec 

Percorso Python:
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoprocAlgos
C:/OSGEO4~1/apps/qgis/./python
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\pigre\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\pigre\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\pigre\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
```

![image](https://user-images.githubusercontent.com/7631137/76160171-178e2880-6128-11ea-92de-e2ddc1942787.png)

**Comment by PedroVenancio** [comment]
Hi @pigreco 

Thanks for testing.

I can not reproduce here. Can you check in a clean profile and with English language?

Because the error points to line 18, that is

from qgis.core import QgsProcessing

and you have

da qgis.core import QgsProcessing

**Comment by pigreco** [comment]
@PedroVenancio 

I used a new profile in English,
the problem is this:

```
An error has occurred while executing Python code: 

SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\script\ScriptAlgorithmProvider.py", line 119, in loadAlgorithms
    alg = ScriptUtils.loadAlgorithm(moduleName, filePath)
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\script\ScriptUtils.py", line 66, in loadAlgorithm
    spec.loader.exec_module(module)
  File "", line 724, in exec_module
  File "", line 860, in get_code
  File "", line 791, in source_to_code
  File "", line 219, in _call_with_frames_removed
  File "C:\Users\pigre\AppData\Roaming\QGIS\QGIS3\profiles\toto\processing\scripts\QGISPolygonSplitting.py", line 18
    da qgis.core import QgsProcessing
          ^
SyntaxError: invalid syntax


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.12.0-București București, cd141490ec 

Python Path:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\toto/python
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\toto/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\toto/python
```

**Comment by PedroVenancio** [comment]
@pigreco 

Can you open your C:\Users\pigre\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\QGISPolygonSplitting.py file and check the line 18?

It should be

`from qgis.core import QgsProcessing`

https://github.com/PedroVenancio/qgis_polygon_splitting/blob/master/QGISPolygonSplitting.py#L18

but from your error log, it seems that you have 

`da qgis.core import QgsProcessing`.

So, I don't know why, but it seems that something had changed the
**from** (english) to **da** (italian) in the python code.

**Comment by pigreco** [comment]
Error found:
all my fault.
I had opened your script and the machine translator changed `from` to` da`.

I fixed everything.
It works fine thanks a lot and sorry for my mistake.

![image](https://user-images.githubusercontent.com/7631137/76166412-a322ac00-615e-11ea-9ade-a8be0355eeff.png)

**Comment by PedroVenancio** [comment]
Great @pigreco thanks for testing!
